#! /usr/bin/env python

import sys
import re
counter = 0

for line in open(sys.argv[1]):
	match1 = re.search(sys.argv[2], line)
	match2 = re.search(sys.argv[3], line)
	counter +=1
	if match1 and match2:
		#print line[:match1.start()] +'\t'+line[match1.start():match1.end()]+'\t'+line[match1.end():match2.start()]+'\t'+line[match2.start():match2.end()]+'\t'+line[match2.end():].rstrip()
		if len(line[match1.end():match2.start()].rstrip()) > 30: print ">"+str(counter)+"\n"+line[match1.end():match2.start()].rstrip()
